language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-support
  licenses:
    - android-sdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "sources;android-27"
  - sdkmanager --list
  - ls /usr/local/android-sdk
  - ls /usr/local/android-sdk/docs

after_success:
  - ./gradlew javadocRelease

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: library/build/docs/javadoc/release
  on:
    branch: master
